// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFIKN4NFtB6GQQdA3cU9tsVQOTbG8Q6Gw',
    appId: '1:616466153366:android:f07bec7935f39b44eb27b7',
    messagingSenderId: '616466153366',
    projectId: 'vessel-vault-ed299',
    storageBucket: 'vessel-vault-ed299.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaQAuMAMl4w5QvD5cj4YoeyqV_JeZYPYc',
    appId: '1:616466153366:web:63ad8a294885845ceb27b7',
    messagingSenderId: '616466153366',
    projectId: 'vessel-vault-ed299',
    authDomain: 'vessel-vault-ed299.firebaseapp.com',
    storageBucket: 'vessel-vault-ed299.firebasestorage.app',
    measurementId: 'G-EQ1PJC4PVB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrDayWHkxDrkaXRmXuSsJ_W7T27T9MxBo',
    appId: '1:616466153366:ios:ab06b58f83fd9b06eb27b7',
    messagingSenderId: '616466153366',
    projectId: 'vessel-vault-ed299',
    storageBucket: 'vessel-vault-ed299.firebasestorage.app',
    androidClientId:
        '616466153366-8sjpecjbsp5oa8clvh22k8velcbe4401.apps.googleusercontent.com',
    iosClientId:
        '616466153366-08l7j93a9ob4ovun4opicvi2uqdm22jc.apps.googleusercontent.com',
    iosBundleId: 'com.example.vesselVault',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrDayWHkxDrkaXRmXuSsJ_W7T27T9MxBo',
    appId: '1:616466153366:ios:ab06b58f83fd9b06eb27b7',
    messagingSenderId: '616466153366',
    projectId: 'vessel-vault-ed299',
    storageBucket: 'vessel-vault-ed299.firebasestorage.app',
    androidClientId:
        '616466153366-8sjpecjbsp5oa8clvh22k8velcbe4401.apps.googleusercontent.com',
    iosClientId:
        '616466153366-08l7j93a9ob4ovun4opicvi2uqdm22jc.apps.googleusercontent.com',
    iosBundleId: 'com.example.vesselVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaQAuMAMl4w5QvD5cj4YoeyqV_JeZYPYc',
    appId: '1:616466153366:web:542e970cfdc5b755eb27b7',
    messagingSenderId: '616466153366',
    projectId: 'vessel-vault-ed299',
    authDomain: 'vessel-vault-ed299.firebaseapp.com',
    storageBucket: 'vessel-vault-ed299.firebasestorage.app',
    measurementId: 'G-29CPXEPZZC',
  );
}
